# Generated by Django 5.2.8 on 2025-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Full Access'), ('Staff', 'View/Add/Update'), ('User', 'View Only')], default='User', max_length=6),
        ),
    ]
