# Generated by Django 5.2.8 on 2025-11-21 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_no', models.IntegerField()),
                ('incoming_goods', models.IntegerField(default=0)),
                ('outgoing_goods', models.IntegerField(default=0)),
                ('inventory', models.IntegerField(default=0)),
                ('remaining_weeks', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('year', 'week_no', 'product')},
            },
        ),
    ]
