# Generated by Django 5.2.8 on 2025-11-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyrecord',
            options={'ordering': ['-year', '-week_no', 'product__jan_code']},
        ),
    ]
