# Generated by Django 5.2.8 on 2025-11-27 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_weeklyrecord_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='created_by',
        ),
    ]
