# Generated by Django 5.2.8 on 2025-12-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_remove_weeklyrecord_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecord',
            name='is_historical',
            field=models.BooleanField(default=False),
        ),
    ]
