# Generated by Django 5.2.8 on 2025-12-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_active'),
        ('weekly', '0005_weeklyrecord_is_historical'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureIncomingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_no', models.IntegerField()),
                ('planned_incoming', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('product', 'year', 'week_no')},
            },
        ),
    ]
