# Generated by Django 5.2.8 on 2025-12-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmaster'),
        ('weekly', '0006_futureincomingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week_no', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total_quantity', models.IntegerField()),
                ('sn', models.CharField(max_length=100)),
                ('no_of_cases', models.IntegerField()),
                ('loose', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_inventory', to='products.productmaster')),
            ],
            options={
                'unique_together': {('year', 'week_no', 'product')},
            },
        ),
    ]
