# Generated by Django 5.2.8 on 2025-12-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0007_weeklyinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyinventory',
            name='sn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
