# Generated by Django 5.2.8 on 2025-12-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0008_alter_weeklyinventory_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyinventory',
            name='sn',
        ),
    ]
