# Generated by Django 5.2.8 on 2025-12-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0009_remove_weeklyinventory_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyinventory',
            name='quantity',
        ),
    ]
