# Generated by Django 5.2.8 on 2025-11-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('Foreign', 'Foreign'), ('Domestic', 'Domestic')], max_length=10)),
                ('lead_time', models.CharField(choices=[('45日', '45日'), ('60日', '60日'), ('45~60日', '45~60日')], max_length=10)),
                ('ordering', models.IntegerField()),
                ('yayoi_code', models.CharField(max_length=50)),
                ('jan_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('handling', models.CharField(blank=True, max_length=200)),
                ('specifications', models.CharField(blank=True, max_length=200)),
                ('monthly_sales_prediction', models.FloatField(default=0)),
                ('forecast', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
