# Generated by Django 5.2.8 on 2025-11-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='forecast',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
