# Generated by Django 5.2.8 on 2025-11-27 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_incoming', models.IntegerField(default=0)),
                ('default_outgoing', models.IntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
