# Generated by Django 5.2.8 on 2025-11-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdefaults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdefaults',
            name='default_outgoing',
        ),
    ]
