# Generated by Django 5.2.8 on 2025-11-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productdefaults_default_outgoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.CharField(blank=True, choices=[('Foreign', 'Foreign'), ('Domestic', 'Domestic')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='handling',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='jan_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='monthly_sales_prediction',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ordering',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='yayoi_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
