# Generated by Django 5.2.8 on 2025-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_classification_alter_product_handling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, choices=[('45日', '45日'), ('60日', '60日'), ('45~60日', '45~60日')], max_length=10, null=True),
        ),
    ]
