# Generated by Django 5.2.8 on 2025-11-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classification',
            field=models.CharField(blank=True, choices=[('国外', '国外'), ('国内', '国内')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_time',
            field=models.CharField(blank=True, choices=[('45', '45'), ('60', '60'), ('45～60', '45～60')], max_length=10, null=True),
        ),
    ]
