# Generated by Django 5.2.8 on 2025-11-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_classification_alter_product_lead_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='yayoi_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
