# Generated by Django 5.2.8 on 2025-12-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdefaults',
            name='default_outgoing',
            field=models.IntegerField(default=0),
        ),
    ]
