# Generated by Django 5.2.8 on 2025-12-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yayoi_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
    ]
