# Generated by Django 5.2.8 on 2025-12-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='sn',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
