# Generated by Django 5.2.8 on 2025-12-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productmaster_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='sn',
        ),
        migrations.AddField(
            model_name='productmaster',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
